sudo sysctl -w dev.tty.ldisc_autoload=0
echo "dev.tty.ldisc_autoload=0" | sudo tee -a /etc/sysctl.conf
sudo sysctl -w fs.protected_fifos=2
echo "fs.protected_fifos=2" | sudo tee -a /etc/sysctl.conf
sudo sysctl -w fs.protected_regular=2
echo "fs.protected_regular=2" | sudo tee -a /etc/sysctl.conf
sudo sysctl -w fs.suid_dumpable=0
echo "fs.suid_dumpable=0" | sudo tee -a /etc/sysctl.conf
sudo sysctl -w kernel.kptr_restrict=2
echo "kernel.kptr_restrict=2" | sudo tee -a /etc/sysctl.conf
sudo sysctl -w kernel.modules_disabled=1
echo "kernel.modules_disabled=1" | sudo tee -a /etc/sysctl.conf
sudo sysctl -w kernel.sysrq=0
echo "kernel.sysrq=0" | sudo tee -a /etc/sysctl.conf
sudo sysctl -w kernel.unprivileged_bpf_disabled=1
echo "kernel.unprivileged_bpf_disabled=1" | sudo tee -a /etc/sysctl.conf
sudo sysctl -w kernel.yama.ptrace_scope=1
echo "kernel.yama.ptrace_scope=1" | sudo tee -a /etc/sysctl.conf
sudo sysctl -w net.ipv4.conf.all.accept_redirects=0
echo "net.ipv4.conf.all.accept_redirects=0" | sudo tee -a /etc/sysctl.conf
sudo sysctl -w net.ipv4.conf.all.log_martians=1
echo "net.ipv4.conf.all.log_martians=1" | sudo tee -a /etc/sysctl.conf
sudo sysctl -w net.ipv4.conf.all.log_martians=1
echo "net.ipv4.conf.all.log_martians=1" | sudo tee -a /etc/sysctl.conf
sudo sysctl -w net.ipv4.conf.all.send_redirects=0
echo "net.ipv4.conf.all.send_redirects=0" | sudo tee -a /etc/sysctl.conf
sudo sysctl -w net.ipv4.conf.default.accept_redirects=0
echo "net.ipv4.conf.default.accept_redirects=0" | sudo tee -a /etc/sysctl.conf
sudo sysctl -w net.ipv4.conf.default.log_martians=1
echo "net.ipv4.conf.default.log_martians=1" | sudo tee -a /etc/sysctl.conf
sudo sysctl -w net.ipv6.conf.all.accept_redirects=0
echo "net.ipv6.conf.all.accept_redirects=0" | sudo tee -a /etc/sysctl.conf
sudo sysctl -w net.ipv6.conf.default.accept_redirects=0
echo "net.ipv6.conf.default.accept_redirects=0" | sudo tee -a /etc/sysctl.conf